### ISSUE TITLE
Python3 module not found: 'zlib'

### ISSUE THREAD

**Issue by PPPPierre** [starfive-tech/VisionFive2#68]
I first found this problem when I compiled a image for my project where need 'requests' module for python.
I chose python-requests in `make buildroot_rootfs-menuconfig` then compile the image based on the steps shown in readme.
Finally I entered the system but I failed in running `python import requests`. It returned an error as followed:

>\>\>\>import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/requests/__init__.py", line 43, in <module>
  File "/usr/lib/python3.9/site-packages/urllib3/__init__.py", line 13, in <module>
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 40, in <module>
  File "/usr/lib/python3.9/site-packages/urllib3/response.py", line 5, in <module>
ModuleNotFoundError: No module named 'zlib'

Then I tried to import directly zlib, it gave me this:

>\>\>\>import zlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'zlib'

The same problem is found with [**tagv3.1.5**](https://github.com/starfive-tech/VisionFive2/releases/tag/VF2_v3.1.5)
The information about this problem is very rare on the internet, the closest one that I found is [this](https://blog.csdn.net/u014088257/article/details/113680402).
It seems the cross-compile tool-chain didnt well compiled libz during the compilation.

Can you fix this problem, thx !

**Comment by andyhu-stf** [comment]
Hi PPPierre, please select `BR2_PACKAGE_PYTHON_REQUESTS` and `BR2_PACKAGE_PYTHON3_ZLIB` through `make buildroot_initramfs-menuconfig` or `make buildroot_rootfs-menuconfig `, then build SDK again. It work well on my board.

if you do not want to build the `work/`  again, you can try:
e.g. for buildroot_initramfs:
```
make -C ./work/buildroot_initramfs/ O=./work/buildroot_initramfs python3-dirclean  # (For BR2_PACKAGE_PYTHON3_ZLIB is in python3)
rm work/buildroot_initramfs/images/rootfs.tar
make -jx
```
